services:
  - type: web
    name: aurora-parasite-pepperstone
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: CTRADER_CLIENT_ID
        value: 27781_BacBxd2DDdHLJIGQJEnwcsbcX7yv6UhwrBM3mpCcCQWqmMydnH
      - key: CTRADER_CLIENT_SECRET
        value: EfdUjsb8xRTrURq1OYkKRC71j7jKg1Le7xSDE0lA2Ml113vkF7
      - key: CTRADER_ACCOUNT_ID
        value: "5285874"
      - key: CTRADER_ENV
        value: demo
      - key: INITIAL_CAPITAL
        value: "500"
      - key: ACCOUNT_TYPE
        value: DEMO
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false