services:
  - type: web
    name: aurora-parasite-pepperstone
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: CTRADER_CLIENT_ID
        value: put here
      - key: CTRADER_CLIENT_SECRET
        value: place here
      - key: CTRADER_ACCOUNT_ID
        value: "place here"
      - key: CTRADER_ENV
        value: demo
      - key: INITIAL_CAPITAL
        value: "500"
      - key: ACCOUNT_TYPE
        value: DEMO
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
